### ISSUE TITLE
Enhanced transaction simulations

### ISSUE THREAD

**Issue by naps62** [ethui/ethui#501]
The wallet already provides simulations automatically whenever a transaction review dialog pops up:

![image](https://github.com/iron-wallet/iron/assets/283819/f5698333-f1f4-47e7-9c7d-ec5e1f242ba1)

We want to improve the capabilities of this dialog, and of simulations as a whole.

Key points (each of which can be its own PR):

- [x] Ability to customize all aspects of a transaction during the dialog (gas, data, value, etc), and see that reflected in the simulation output in near-real time
- [x] Ability to see the decoded call data, based on ABI information, with all the arguments being used, and the ability to edit them as well (e.g.: edit the amount of an ERC20 transaction), and just like above, see the real-time feedback in the simulation output
- [x] Show more intelligent information based on the output: ERC20 transfers, ERC721 transfers, ERC20 approval changes.
- [x] Detect if the destination contract is one we haven't interacted with before, or has been deployed recently, and display a warning in such cases (#610 )
- [x] Ability to select a transaction from the wallet's history, and ask to "send it again", filling in the dialog & simulation with those parameters. This may be useful mostly for developers wanting to take repeated actions, or test the same interaction with slightly different params (#611 )

**Comment by ABZerra** [comment]
Nothing to add, looks awesome.

**Comment by naps62** [comment]
Finalized in #661 with the ability to edit individual tx fields
